### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by apjansing** [gregory2718/SUNY_MAT560#2] opened 2018-05-03 22:58 UTC
https://github.com/gregory2718/SUNY_MAT560/blob/563d4418cbe4007c89218f5dbe6a49ee65c96595/project/src/polyplate/Simulator.py#L45

After updating the [recreating_initial_conditions.py](https://github.com/gregory2718/SUNY_MAT560/blob/master/project/src/recreating_initial_conditions.py), I am receiving the following error.

```
fenics@647c11e868bf:~/shared$ python recreating_initial_conditions.py gmsh/demo/meshes/plate/plate.xml
Computing eigenvalues. This can take a minute.
('found: ', 252)
Traceback (most recent call last):
  File "recreating_initial_conditions.py", line 29, in <module>
    main(argv[1])
  File "recreating_initial_conditions.py", line 23, in main
    simulator.evaluate(t)
  File "/home/fenics/shared/polyplate/Simulator.py", line 45, in evaluate
    f.vector()[:] = vec
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/la.py", line 1404, in __setslice__
    self[indices] = values
  File "/usr/lib/python2.7/dist-packages/dolfin/cpp/la.py", line 1506, in __setitem__
    values = asarray(values, dtype=float_)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
Aborted
```

Do you know what this might be caused by?

**Comment by apjansing** [comment] 2018-05-03 22:58
@gregory2718

**Comment by gregory2718** [comment] 2018-05-03 23:13
The problem is likely that the vectors are different sized, because the eigenvectors were in our U * V function space, and f is in U. It's possible that replacing the line with`f.vector()[:] = vec[:len(f.vector()[:])]` will fix it.

**Comment by gregory2718** [comment] 2018-05-03 23:16
It would help if you could post what values `f.vector()[:]` and `vec` have.

**Comment by apjansing** [comment] 2018-05-04 00:12
```
print('f.vector()[:]', f.vector()[:])
print('vec[:len(f.vector()[:])]', vec[:len(f.vector()[:])])
```
results in
```
('f.vector()[:]', <dolfin.cpp.la.GenericVector; proxy of <Swig Object of type 'std::shared_ptr< dolfin::GenericVector > *' at 0x7fc17d1c3360> >)
('vec[:len(f.vector()[:])]', UFL conditions cannot be evaluated as bool in a Python context.
```

**Comment by apjansing** [comment] 2018-05-04 00:14
```print('vec', vec)```
also gives 
```('vec', UFL conditions cannot be evaluated as bool in a Python context.```

**Comment by apjansing** [comment] 2018-05-04 00:52
```print(len(f.vector()[:]))
print(len(vec))
```

gives 
```
126
252
```

**Comment by gregory2718** [comment] 2018-05-04 01:00
Well, at least I was right about the size mismatch. I'll figure out how to reconcile the types tomorrow.

**Comment by apjansing** [comment] 2018-05-04 01:15
so maybe something a little more upstream from this problem....

https://github.com/gregory2718/SUNY_MAT560/blob/563d4418cbe4007c89218f5dbe6a49ee65c96595/project/src/polyplate/Simulator.py#L27
https://github.com/gregory2718/SUNY_MAT560/blob/563d4418cbe4007c89218f5dbe6a49ee65c96595/project/src/polyplate/Simulator.py#L28

Should these both have ```.vector()``` on them?

**Comment by apjansing** [comment] 2018-05-04 01:16
Adding the ```.vector()``` does cause the following problem

```
Traceback (most recent call last):
  File "recreating_initial_conditions.py", line 29, in <module>
    main(argv[1])
  File "recreating_initial_conditions.py", line 19, in main
    simulator = Simulator(mesh, U, eigenVectors, eigenValues)
  File "/home/fenics/shared/polyplate/Simulator.py", line 27, in __init__
    self.pEig = self.inEigenBasis(self.pVec.vector())
  File "/home/fenics/shared/polyplate/Simulator.py", line 32, in inEigenBasis
    return array([dot(vec, e) / dot(e, e) for e in self.eVecs])
ValueError: shapes (126,) and (252,) not aligned: 126 (dim 0) != 252 (dim 0)
Aborted
```

**Comment by gregory2718** [comment] 2018-05-05 16:44
Adding `.vector()` solved the problem. I'm closing this issue.

**Closed** 2018-05-05 16:47 UTC
